[package]
name = "vle"
version = "0.3.0"
edition = "2024"

[[bin]]
name = "vle"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
crossterm = "0.29"
logos = "0.16"
ratatui = "0.30"
ropey = "1.6"
unicode-truncate = "2.0"
