[package]
name = "vle"
version = "0.7.0"
edition = "2024"
license = "MIT/Apache-2.0"

[[bin]]
name = "vle"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.29"
imara-diff = "0.2"
lazy-regex = "3.5"
logos = "0.16"
ratatui = "0.30"
ropey = "1.6"
unicode-truncate = "2.0"
unicode-width = "0.2"
